# v3 syntax
version: '3'

# Named volumes
volumes:
  # MySQL Data
  tiny-mysql-data:
    driver: local

services:  
  # MySQL (5.7)
  mysql:
    image: mysql:5.5
    container_name: tiny-mysql
    volumes:
      - tiny-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.4-nginx
    container_name: tiny-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql